### ISSUE TITLE
[fr] make app.ts export an asynchronous function

### ISSUE THREAD

**Issue by FossPrime** [feathersjs/feathers-chat#223]
https://github.com/feathersjs/feathers-chat/blob/f7f53dd760dec893bf754d4be774980a166d4639/typescript/src/app.ts#L55

This makes the entire feathers setup less flexible. If someone needs to fetch secrets asynchronously, ask for user input during dev etc, abstract away configuration, or run multiple instance in the same process for testing etc.

# proposed solution

Export an async setup function by default. One that stops shy of polluting the global state by opening a port.
Example: https://github.com/feathersjs/playground/blob/76e411d73be3ada3d74c1ac8c3bd395883532383/starter/api/app.ts#L24

Exporting a setup class would also work... Though may not be super useful, aside from allowing meta configuration, such as asking for an app instance that has no app hooks.

P.S. I preferred the old naming scheme... `/typescript` and `client.ts` are too generic single word terms. Typescript is like saying English. Instead of typescript consider api or api-server. Instead of client.ts consider api-client.ts, to clear up confusion between client.js, react, socketio and feathers client.

**Comment by daffl** [comment]
Doing asynchronous configuration and setup things is essentially what [app.setup and teardown](https://dove.feathersjs.com/api/hooks.html#setup-and-teardown) hooks are intended for.

I'm not sure if it's worth changing the naming again. It's already been linked in a few places in the docs and other (archived) repositories.

**Comment by daffl** [comment]
One thing to note is that it requires an explicit call to `await app.setup()` or `await app.listen()`

**Comment by FossPrime** [comment]
> I'm not sure if it's worth changing the naming again

Agreed... changing names is usually undesireable, which is why more future-resistant names are better.

I'm running across tons of decisions in feathers where a two word term would have been better than a single word term.

<table>
<tr>
    <th> Worse
    <th> Better
    <th> Why
<tr>
    <td> @feathersjs/memory
    <td> <a href="https://www.npmjs.com/package/@feathersjs/adapter-memory">@feathersjs/adapter-memory</a>
    <td> Purpose too ambiguous
<tr>
    <td> @feathersjs/socketio
    <td> @feathersjs/socketio-plugin
    <td> Looks like a fork/replacement for socketio.
<tr>
	<td> express.static
	<td> express.serveStatic
	<td> conflict
<tr>
	<td> typescript
	<td>  typescript-api
	<td> ambiguous
<tr>
	<td> express.handler
	<td> express.errorHandler
    <td> ambiguous
</table>

The cost of an extra word is rarely high enough to outweigh the ambiguity of single word exports in a public facing library or API.

**Comment by daffl** [comment]
I'm not sure if the benefits outweigh the effort and potential downsides like broken links and people downloading the wrong packages. Renaming a GitHub repository is easy since you get redirects but this is not the case for folders and moving an npm package is not even possible (and nobody ever reads deprecation notices).

I found that most issues are not about naming (so far there weren't any complaints about this) but rather a lack of or inconsistent documentation which is definitely always something that should be addressed. If you want, you are welcome to rename the `typescript` folder here back to `typescript-api` and update links pointing to it like in the documentation. 
`express.errorHandler` [already exists](https://dove.feathersjs.com/api/express.html#errorhandler) and `express.static` is [aliased as `serveStatic`](https://dove.feathersjs.com/api/express.html#built-ins) as well.
