### ISSUE TITLE
Signup.js middleware - only authenticated users 

### ISSUE THREAD

**Issue by idealley** [feathersjs/feathers-chat#52]
If you want to have only "admin users" that can create accounts, the middleware opens a security breach as it allows non logged in people to create users.

if in the users service you protect the create method as such:

```
  create: [
    auth.verifyToken(),
    auth.populateUser(),
    auth.hashPassword(),
    auth.restrictToAuthenticated(),
    auth.restrictToRoles({
      roles: ['admin'],
      fieldName: 'permissions'
    })
  ],
```

The API endpoint `POST /users` is effectively disabled for non 'admin' users
But the middleware does allow the creation of new users:

```
    app.service('users').create({
      email: body.email,
      password: body.password,
      permissions: 'registered'
    })
```

The solution could be to create a "signup service" with one method "create"

```
  setup(app) {
    this.app = app;
  }

  create(data, params) {
      this.app.service('users').create({
        email: data.email,
        password: data.password,
        permissions: 'registered'
    })
    return Promise.resolve({status:200, data: data, message: 'User created (registered)'});
  }
```

Then do not forget the restriction in the `create: []` of the before hook.

Error need to be managed.

**Comment by daffl** [comment]
Thank you for pointing that out @idealley. The difficulties of securing middleware is one of the reasons we made the release of Feathers that got soft-launched yesterday more API centric.

If you `npm install feathers-cli` at v2.0.0 or later you can see it will generate an application similar to what is in the master branch of this repository now. All [framework applications](https://github.com/feathersjs/feathers-chat/tree/master/public) have been moved to do signup and login completely on the client so in order to do what you are suggesting you will not just have to secure the [create endpoint](https://github.com/feathersjs/feathers-chat/blob/master/src/services/users/users.hooks.js#L13) with the `authenticate` hook and a hook that checks the user role.
